const SHOW_SNACKBAR = "SHOW_SNACK_BAR";
const HIDE_SNACKBAR = "HIDE_SNACK_BAR";
const SHOW_LOADING = "SHOW_LOADING";
const HIDE_LOADING = "HIDE_LOADING";
const HIDE_NOTIFICATION_SNACKBAR = "HIDE_NOTIFICATION_SNACKBAR";
const HIDE_UPDATE_SNACKBAR = "HIDE_UPDATE_SNACKBAR";
const SHOW_NOTIFICATION_SNACKBAR = "SHOW_NOTIFICATION_SNACKBAR"
const SHOW_UPDATE_SNACKBAR = "SHOW_UPDATE_SNACKBAR";
const UPDATE_APP_VERSION = "UPDATE_APP_VERSION"
export {
  SHOW_SNACKBAR,
  HIDE_SNACKBAR,
  SHOW_LOADING,
  HIDE_LOADING,
  HIDE_NOTIFICATION_SNACKBAR,
  HIDE_UPDATE_SNACKBAR,
  SHOW_NOTIFICATION_SNACKBAR,
  SHOW_UPDATE_SNACKBAR,
  UPDATE_APP_VERSION
};
