const SHOW_SNACKBAR = "SHOW_SNACK_BAR";
const HIDE_SNACKBAR = "HIDE_SNACK_BAR";
const SHOW_LOADING = "SHOW_LOADING";
const HIDE_LOADING = "HIDE_LOADING";

const ADD_USER = "ADD_USER";
const EDIT_USER = "EDIT_USER";
const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
const GET_ALL_USER = "GET_ALL_USER";
const GET_USER = "GET_USER";
const UPDATE_ROLE_USER = "UPDATE_ROLE_USER";
const SIGN_IN_SUCCESS = "SIGN_IN";
const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
const GET_ALL_ROLE_SUCCESS = "GET_ALL_ROLE_SUCCESS";
const GET_ALL_SHIFT_SUCCESS = "GET_ALL_SHIFT_SUCCESS";
const GET_TIME_KEEPING_NOTIFICATION_SUCCESS = "GET_TIME_KEEPING_NOTIFICATION_SUCCESS";
const GET_NOTIFY_FOR = "GET_NOTIFY_FOR";
const UPDATE_TIME_KEEPING_NOTIFICATION_SUCCESS = "UPDATE_TIME_KEEPING_NOTIFICATION_SUCCESS";
const UPDATE_SHIFTS_SUCCESS = "UPDATE_SHIFTS_SUCCESS";
const UPDATE_IS_ALL_VALID = "UPDATE_IS_ALL_VALID";
const GET_ALL_ORGANIZATION_SUCCESS = "GET_ALL_ORGANIZATION_SUCCESS";
const ADD_ORGANIZATION_SUCCESS = "ADD_ORGANIZATION_SUCCESS";
const DELETE_ORGANIZATION_SUCCESS = "DELETE_ORGANIZATION_SUCCESS";
const UPDATE_ORGANIZATION_SUCCESS = "UPDATE_ORGANIZATION_SUCCESS";
const GET_ALL_FEATURES_SUCCESS = "GET_ALL_FEATURES_SUCCESS";
const GET_ALL_LOG_SUCCESS = "GET_ALL_LOG_SUCCESS";
const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
const UPDATE_MY_INFO_SUCCESS = "UPDATE_MY_INFO_SUCCESS";
const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
const GET_ALL_CAMERA_SUCCESS = "GET_ALL_CAMERA_SUCCESS";
const GET_ALL_EMPLOYEE_SUCCESS = "GET_ALL_EMPLOYEE_SUCCESS";
const UPDATE_PAGE_INFO = "UPDATE_PAGE_INFO";
const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
const GET_ALL_LOCATION_SUCCESS = "GET_ALL_LOCATION_SUCCESS";
const ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS";
const UPDATE_LOCATION_SUCCESS = "UPDATE_LOCATION_SUCCESS";
const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
const UPDATE_FILTER_LOCATION = "UPDATE_FILTER_LOCATION";
const UPDATE_EXPANDED_LIST = "UPDATE_EXPANDED_LIST";
const SET_ALL_EXPENDED_LIST = "SET_ALL_EXPENDED_LIST";
const UPDATE_ALL_EXPANDED_LIST = "UPDATE_ALL_EXPANDED_LIST";
const UPDATE_ITEM_CHOOSED = "UPDATE_ITEM_CHOOSED";
const CHANGE_MANAGER_SUCCESS = "CHANGE_MANAGER_SUCCESS";
const ADD_CAMERA_SUCCESS = "ADD_CAMERA_SUCCESS";
const GET_ALL_BRAND_SUCCESS = "GET_ALL_BRAND_SUCCESS";
const DELETE_CAMERA_SUCCESS = "DELETE_CAMERA_SUCCESS";
const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
const UPDATE_CAMERA_SUCCESS = "UPDATE_CAMERA_SUCCESS";
const GET_ALL_IN_OUT_HISTORIES_SUCCESS = "GET_ALL_IN_OUT_HISTORIES_SUCCESS";
const GET_ALL_TO_DAY_IN_OUT_HISTORIES_SUCCESS = "GET_ALL_TO_DAY_IN_OUT_HISTORIES_SUCCESS";
const ADD_IN_OUT_HISTORY_SUCCESS = "ADD_IN_OUT_HISTORY_SUCCESS";
const ADD_TO_DAY_IN_OUT_HISTORY_SUCCESS = "ADD_TO_DAY_IN_OUT_HISTORY_SUCCESS";
const UPDATE_TO_DAY_IN_OUT_HISTORY_SUCCESS = "UPDATE_TO_DAY_IN_OUT_HISTORY_SUCCESS"; // For testing
const GET_ALL_NOTIFICATION_HISTORIES_SUCCESS = "GET_ALL_NOTIFICATION_HISTORIES_SUCCESS";
const ADD_NOTIFICATION_HISTORY_SUCCESS = "ADD_NOTIFICATION_HISTORY_SUCCESS";
const GET_ALL_AREA_RESTRICTION_SUCCESS = "GET_ALL_AREA_RESTRICTION_SUCCESS";
const ADD_AREA_RESTRICTION_SUCCESS = "ADD_AREA_RESTRICTION_SUCCESS";
const UPDATE_AREA_RESTRICTION_SUCCESS = "UPDATE_AREA_RESTRICTION_SUCCESS";
const DELETE_AREA_RESTRICTION_SUCCESS = "DELETE_AREA_RESTRICTION_SUCCESS";
const GET_ALL_AREA_RESTRICTION_NOTIFICATION_SUCCESS =
  "GET_ALL_AREA_RESTRICTION_NOTIFICATION_SUCCESS";
const UPDATE_AREA_RESTRICTION_NOTIFICATION_SUCCESS = "UPDATE_AREA_RESTRICTION_NOTIFICATION_SUCCESS";
const UPDATE_AREA_USER_ATTENDANCE_CHOOSED = "UPDATE_AREA_USER_ATTENDANCE_CHOOSED";
const UPDATE_FILTER_AREA_RESTRICTION = "UPDATE_FILTER_AREA_RESTRICTION";
const GET_USER_ATTENDANCE_ITEMS_SUCCESS = "GET_USER_ATTENDANCE_ITEMS_SUCCESS";
const ADD_USER_ATTENDANCE_ITEM_SUCCESS = "ADD_USER_ATTENDANCE_ITEM_SUCCESS";
const UPDATE_USER_ATTENDANCE_ITEM_SUCCESS = "UPDATE_USER_ATTENDANCE_ITEM_SUCCESS";
const UPDATE_CONFIRM_AUDIO = "UPDATE_CONFIRM_AUDIO";
const UPDATE_STATUS_AUDIO = "UPDATE_STATUS_AUDIO";
const UPDATE_HAS_NOTIFICATION_AUDIO = "UPDATE_HAS_NOTIFICATION_AUDIO";
const UPDATE_EMPLOYEE_CHOOSED = "UPDATE_EMPLOYEE_CHOOSED";
const UPDATE_AREA_RESTRICTION_CHOOSED = "UPDATE_AREA_RESTRICTION_CHOOSED";
const UPDATE_FILTER_USER_LOG = "UPDATE_FILTER_USER_LOG";
const UPDATE_FILTER_NOTIFICATION_HISTORY = "UPDATE_FILTER_NOTIFICATION_HISTORY";
const UPDATE_TOGGLE_NOTIFICATION_HISTORY = "UPDATE_TOGGLE_NOTIFICATION_HISTORY";
const UPDATE_FILTER_CAMERA = "UPDATE_FILTER_CAMERA";
const UPDATE_FILTER_EMPLOYEE = "UPDATE_FILTER_EMPLOYEE";
const UPDATE_STATUS_IMPORT_FILE = "UPDATE_STATUS_IMPORT_FILE";
const UPDATE_NOTIFICATION_STATUS = "UPDATE_NOTIFICATION_STATUS";
const RE_SEND_CODE_EMPLOYEE_SUCCESS = "RE_SEND_CODE_EMPLOYEE_SUCCESS";
const UPDATE_FILTER_USER = "UPDATE_FILTER_USER";
const ADD_GUEST = "ADD_GUEST";
const UPDATE_FILTER_IN_OUT_HISTORY = "UPDATE_FILTER_IN_OUT_HISTORY";
const ADD_CAMERA_LIST_ID_SUCCESS = "ADD_CAMERA_LIST_ID_SUCCESS";
const UPDATE_FILTER_ORGANIZATION = "UPDATE_FILTER_ORGANIZATION";
const SAVE_NOTICE_TAB_NOTIFICATION_DASHBOARD = "SAVE_NOTICE_TAB_NOTIFICATION_DASHBOARD";
const GET_ALL_UNKNOWN_HISTORIES_SUCCESS = "GET_ALL_UNKNOWN_HISTORIES_SUCCESS";
const UPDATE_FILTER_UNKNOWN_HISTORY = "UPDATE_FILTER_UNKNOWN_HISTORY";
const ADD_UNKNOWN_HISTORY_SUCCESS = "ADD_UNKNOWN_HISTORY_SUCCESS";
const DELETE_SHIFT_SUCCESS = "DELETE_SHIFT_SUCCESS";
const UPDATE_FILTER_SHIFT = "UPDATE_FILTER_SHIFT";
const GET_EMPLOYEE_SHIFT = "GET_EMPLOYEE_SHIFT";
const GET_DEPARTMENT_SHIFT = "GET_DEPARTMENT_SHIFT";
const GET_ALL_DEPARTMENT_SUCCESS = "GET_ALL_DEPARTMENT_SUCCESS";
const UPDATE_DEPARTMENT_SHIFT = "UPDATE_DEPARTMENT_SHIFT";
const UPDATE_FILTER_DEPARTMENT = "UPDATE_FILTER_DEPARTMENT";
const DELETE_DEPARTMENT_SUCCESS = "DELETE_DEPARTMENT_SUCCESS";
const UPDATE_ACTION_TYPE_DEPARTMENT = "UPDATE_ACTION_TYPE_DEPARTMENT";
const UPDATE_FILTER_REPORT = "UPDATE_FILTER_REPORT";
const UPDATE_EMPLOYEE_LIST_REPORT = "UPDATE_EMPLOYEE_LIST_REPORT";
const UPDATE_DEPARTMENT_LIST_REPORT = "UPDATE_DEPARTMENTS_NAME_REPORT";
const UPDATE_CURRENT_DEPARTMENT_LIST_REPORT = "UPDATE_CURRENT_DEPARTMENT_LIST_REPORT";
const UPDATE_SUB_FILTER_REPORT = "UPDATE_SUB_FILTER_REPORT";
const UPDATE_TYPE_REPORT = "UPDATE_TYPE_REPORT";
const UPDATE_DATA_CHECK_IN_API = "UPDATE_DATA_CHECK_IN_API";
const UPDATE_DATA_CHECK_IN_FILTER = "UPDATE_DATA_CHECK_IN_FILTER";
const UPDATE_DATA_ABSENT_API = "UPDATE_DATA_ABSENT_API";
const UPDATE_DATA_ABSENT_FILTER = "UPDATE_DATA_ABSENT_FILTER";
const UPDATE_DATA_TIME_KEEPING_API = "UPDATE_DATA_TIME_KEEPING_API";
const UPDATE_DATA_TIME_KEEPING_FILTER = "UPDATE_DATA_TIME_KEEPING_FILTER";
const UPDATE_MAX_IN_OUT = "UPDATE_MAX_IN_OUT";
const SET_ALL_EXPENDED_LIST_REPORT = "SET_ALL_EXPENDED_LIST_REPORT";
const UPDATE_EXPANDED_LIST_REPORT = "UPDATE_EXPANDED_LIST_REPORT";
const UPDATE_CAMERAS_CHECKIN_HISTORY = "UPDATE_CAMERAS_CHECKIN_HISTORY";
const UPDATE_APP_VERSION = "UPDATE_APP_VERSION";
const SHOW_UPDATE_SNACKBAR = "SHOW_UPDATE_SNACKBAR";
const HIDE_UPDATE_SNACKBAR = "HIDE_UPDATE_SNACKBAR";
const UPDATE_CAN_DELETE_USER = "UPDATE_CAN_DELETE_USER";
const GET_ALL_TIME_KEEPING_HISTORIES_SUCCESS = "GET_ALL_TIME_KEEPING_HISTORIES_SUCCESS";
const UPDATE_FILTER_TIME_KEEPING = "UPDATE_FILTER_TIME_KEEPING";
const SHOW_NOTIFICATION_SNACKBAR = "SHOW_NOTIFICATION_SNACKBAR";
const HIDE_NOTIFICATION_SNACKBAR = "HIDE_NOTIFICATION_SNACKBAR";
const UPDATE_IS_DISCONNECT = "UPDATE_IS_DISCONNECT";
const DELETE_CHECKIN_ITEM = "DELETE_CHECKIN_ITEM";
const UPDATE_STATUS_EXPORT_FILE_LATE = "UPDATE_STATUS_EXPORT_FILE_LATE";
const UPDATE_STATUS_EXPORT_FILE_TIMEKEEPING = "UPDATE_STATUS_EXPORT_FILE_TIMEKEEPING";
const UPDATE_CAMERAIDS_DISCONNECT = "UPDATE_CAMERAIDS_DISCONNECT";
export {
  SHOW_SNACKBAR,
  HIDE_SNACKBAR,
  SHOW_LOADING,
  HIDE_LOADING,
  ADD_USER,
  EDIT_USER,
  DELETE_USER_SUCCESS,
  GET_USER,
  GET_ALL_USER,
  UPDATE_ROLE_USER,
  SIGN_IN_SUCCESS,
  GET_ALL_USER_SUCCESS,
  GET_ALL_ROLE_SUCCESS,
  GET_ALL_SHIFT_SUCCESS,
  GET_TIME_KEEPING_NOTIFICATION_SUCCESS,
  UPDATE_TIME_KEEPING_NOTIFICATION_SUCCESS,
  UPDATE_SHIFTS_SUCCESS,
  GET_ALL_ORGANIZATION_SUCCESS,
  ADD_ORGANIZATION_SUCCESS,
  DELETE_ORGANIZATION_SUCCESS,
  UPDATE_ORGANIZATION_SUCCESS,
  GET_ALL_FEATURES_SUCCESS,
  GET_ALL_LOG_SUCCESS,
  GET_NOTIFY_FOR,
  UPDATE_USER_SUCCESS,
  UPDATE_MY_INFO_SUCCESS,
  LOG_OUT_SUCCESS,
  GET_ALL_CAMERA_SUCCESS,
  GET_ALL_EMPLOYEE_SUCCESS,
  ADD_EMPLOYEE_SUCCESS,
  UPDATE_EMPLOYEE_SUCCESS,
  GET_ALL_LOCATION_SUCCESS,
  ADD_LOCATION_SUCCESS,
  UPDATE_LOCATION_SUCCESS,
  DELETE_LOCATION_SUCCESS,
  UPDATE_FILTER_LOCATION,
  CHANGE_MANAGER_SUCCESS,
  ADD_CAMERA_SUCCESS,
  GET_ALL_BRAND_SUCCESS,
  DELETE_CAMERA_SUCCESS,
  DELETE_EMPLOYEE_SUCCESS,
  UPDATE_CAMERA_SUCCESS,
  GET_ALL_IN_OUT_HISTORIES_SUCCESS,
  ADD_IN_OUT_HISTORY_SUCCESS,
  GET_ALL_NOTIFICATION_HISTORIES_SUCCESS,
  GET_ALL_AREA_RESTRICTION_SUCCESS,
  ADD_AREA_RESTRICTION_SUCCESS,
  UPDATE_AREA_RESTRICTION_SUCCESS,
  DELETE_AREA_RESTRICTION_SUCCESS,
  GET_ALL_AREA_RESTRICTION_NOTIFICATION_SUCCESS,
  UPDATE_AREA_RESTRICTION_NOTIFICATION_SUCCESS,
  UPDATE_AREA_USER_ATTENDANCE_CHOOSED,
  GET_USER_ATTENDANCE_ITEMS_SUCCESS,
  ADD_USER_ATTENDANCE_ITEM_SUCCESS,
  UPDATE_USER_ATTENDANCE_ITEM_SUCCESS,
  UPDATE_CONFIRM_AUDIO,
  UPDATE_STATUS_AUDIO,
  UPDATE_HAS_NOTIFICATION_AUDIO,
  UPDATE_EMPLOYEE_CHOOSED,
  UPDATE_AREA_RESTRICTION_CHOOSED,
  UPDATE_FILTER_USER_LOG,
  UPDATE_FILTER_NOTIFICATION_HISTORY,
  UPDATE_CURRENT_DEPARTMENT_LIST_REPORT,
  UPDATE_FILTER_CAMERA,
  UPDATE_FILTER_EMPLOYEE,
  UPDATE_NOTIFICATION_STATUS,
  UPDATE_TOGGLE_NOTIFICATION_HISTORY,
  RE_SEND_CODE_EMPLOYEE_SUCCESS,
  UPDATE_FILTER_USER,
  ADD_GUEST,
  UPDATE_FILTER_IN_OUT_HISTORY,
  ADD_CAMERA_LIST_ID_SUCCESS,
  UPDATE_FILTER_ORGANIZATION,
  UPDATE_IS_ALL_VALID,
  SAVE_NOTICE_TAB_NOTIFICATION_DASHBOARD,
  UPDATE_FILTER_AREA_RESTRICTION,
  ADD_NOTIFICATION_HISTORY_SUCCESS,
  GET_ALL_TO_DAY_IN_OUT_HISTORIES_SUCCESS,
  ADD_TO_DAY_IN_OUT_HISTORY_SUCCESS,
  GET_ALL_UNKNOWN_HISTORIES_SUCCESS,
  UPDATE_FILTER_UNKNOWN_HISTORY,
  ADD_UNKNOWN_HISTORY_SUCCESS,
  UPDATE_EXPANDED_LIST,
  UPDATE_ALL_EXPANDED_LIST,
  UPDATE_ITEM_CHOOSED,
  DELETE_SHIFT_SUCCESS,
  UPDATE_FILTER_SHIFT,
  GET_EMPLOYEE_SHIFT,
  GET_ALL_DEPARTMENT_SUCCESS,
  UPDATE_DEPARTMENT_SHIFT,
  UPDATE_FILTER_DEPARTMENT,
  SET_ALL_EXPENDED_LIST,
  DELETE_DEPARTMENT_SUCCESS,
  UPDATE_ACTION_TYPE_DEPARTMENT,
  GET_DEPARTMENT_SHIFT,
  UPDATE_FILTER_REPORT,
  UPDATE_EMPLOYEE_LIST_REPORT,
  UPDATE_DEPARTMENT_LIST_REPORT,
  UPDATE_SUB_FILTER_REPORT,
  UPDATE_TYPE_REPORT,
  UPDATE_MAX_IN_OUT,
  SET_ALL_EXPENDED_LIST_REPORT,
  UPDATE_EXPANDED_LIST_REPORT,
  UPDATE_DATA_CHECK_IN_API,
  UPDATE_DATA_CHECK_IN_FILTER,
  UPDATE_DATA_ABSENT_API,
  UPDATE_DATA_ABSENT_FILTER,
  UPDATE_DATA_TIME_KEEPING_API,
  UPDATE_DATA_TIME_KEEPING_FILTER,
  UPDATE_PAGE_INFO,
  UPDATE_STATUS_IMPORT_FILE,
  UPDATE_CAMERAS_CHECKIN_HISTORY,
  UPDATE_APP_VERSION,
  SHOW_UPDATE_SNACKBAR,
  HIDE_UPDATE_SNACKBAR,
  UPDATE_CAN_DELETE_USER,
  GET_ALL_TIME_KEEPING_HISTORIES_SUCCESS,
  UPDATE_FILTER_TIME_KEEPING,
  UPDATE_TO_DAY_IN_OUT_HISTORY_SUCCESS,
  SHOW_NOTIFICATION_SNACKBAR,
  HIDE_NOTIFICATION_SNACKBAR,
  UPDATE_IS_DISCONNECT,
  DELETE_CHECKIN_ITEM,
  UPDATE_STATUS_EXPORT_FILE_LATE,
  UPDATE_STATUS_EXPORT_FILE_TIMEKEEPING,
  UPDATE_CAMERAIDS_DISCONNECT,
};
