const SHOW_SNACKBAR = "SHOW_SNACK_BAR";
const HIDE_SNACKBAR = "HIDE_SNACK_BAR";
const SHOW_LOADING = "SHOW_LOADING";
const HIDE_LOADING = "HIDE_LOADING";

export {
  SHOW_SNACKBAR,
  HIDE_SNACKBAR,
  SHOW_LOADING,
  HIDE_LOADING,
};
